// Hand-authored 32x32 pixel-art sprites for the nine producer tiers.
// Top-down (dorsal) specimen view, head pointing north, near bilateral symmetry.
// '.' is transparent. Light source: top-left.

module.exports = {
  ant: {
    w: 32, h: 32,
    palette: { "k": "#221109", "d": "#4a2410", "b": "#7a3f18", "l": "#a35c26", "h": "#d08b44", "e": "#f2e2c0" },
    rows: [
      "................................",
      "................................",
      ".......l................l.......",
      "........b.....l..l.....b........",
      ".........b..ld....dl..b.........",
      "..........b..kkkkkk..b..........",
      "...........bklhbbbdkb...........",
      "...........kehhbbbkkk...........",
      "...........kklhbbbdkk...........",
      "............kkbbbbdk............",
      ".............kbbbdk.............",
      ".........dddklhbbbdkddd.........",
      "........d...kbhbbbdk...d........",
      ".......k..ddkbbbbbdkdd..k.......",
      ".........d..klhbbbdk..d.........",
      "........k.ddkbbbbbdkdd.k........",
      ".........d...kkbbdk...d.........",
      "........k.....kbbk.....k........",
      ".............klhbdk.............",
      "............klhbbbdk............",
      "...........klhhbbbbdk...........",
      "...........khehbbbbdk...........",
      "...........klhbbbbddk...........",
      "...........kbbbbbbddk...........",
      "............kbbbbddk............",
      "............kkbbbdkk............",
      ".............kkkkkk.............",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................"
    ]
  },

  aphid: {
    w: 32, h: 32,
    palette: { "k": "#16290e", "d": "#40701f", "b": "#74ad3e", "l": "#9ed35f", "h": "#c8f090", "e": "#f4ffdc" },
    rows: [
      "................................",
      ".......l................l.......",
      "........b..............b........",
      ".........b............b.........",
      "..........b..........b..........",
      "...........b........b...........",
      "............bkkkkkkb............",
      "............kehbbbkk............",
      "............kklbbbdk............",
      "............klhbbbdk............",
      "..........dklhhbbbbdkd..........",
      ".........d.khhbbbbbdk.d.........",
      "........k.klhbbbbbbbdk.k........",
      ".........dkbhhbbbbbbdkd.........",
      "........dkbhhbbbbbbbbdkd........",
      ".......k.kbhebbbbbbbbdk.k.......",
      "........dkblhbbbbbbbbdkd........",
      ".......k.kblbbbbbbbbbdk.k.......",
      ".........kbbbbbbbbbbbdk.........",
      "..........kbbbbbbbbbdk..........",
      "..........klbbbbbbbbdk..........",
      ".........l.kbbbbbbbdk.l.........",
      "........l..kbbbbbbbdk..l........",
      "........l...kbbbbbdk...l........",
      ".............kbbbdk.............",
      "..............kkkk..............",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................",
      "................................"
    ]
  },

  ladybug: {
    w: 32, h: 32,
    palette: { "k": "#2b0a07", "d": "#7d1210", "b": "#c81c1c", "l": "#e93c28", "h": "#ff7a55", "e": "#ffeadd", "w": "#f2ece0", "n": "#17110e" },
    rows: [
      "................................",
      "................................",
      "............n......n............",
      ".............n....n.............",
      ".............nnnnnn.............",
      "............nnennnnn............",
      "...........kwwnnnnnwk...........",
      "..........kwwnnnnnnwwk..........",
      "........kknwnnnnnnnnwnkk........",
      ".......kkdlhbbbkkbbbbddk........",
      ".....k.kdlhhbbbkkbbbbbddk.k.....",
      "......kdlhehbbbkkbbbbbbddk......",
      "......kdbhhbbnnkknnbbbbbdk......",
      ".....kdblhbbbnnkknnbbbbbbdk.....",
      ".....kdbnnnbbnbkkbnbbnnnbdk.....",
      ".....kdbnnnbbbbkkbbbbnnnbdk.....",
      "....kkdbnnbbbbbkkbbbbbnnbdkk....",
      "...k.kdbbbbbbbbkkbbbbbbbbdk.k...",
      ".....kdbbbbbbbbkkbbbbbbbbdk.....",
      ".....kdbnnnbbbbkkbbbbnnnbdk.....",
      "......kdnnnbbbbkkbbbbnnndk......",
      "......kdnnbbbbbkkbbbbbnndk......",
      ".....k.kdbbbbbbkkbbbbbbdk.k.....",
      "......k.kdbbbbbkkbbbbbdk.k......",
      ".........kdbbbbkkbbbbdk.........",
      "..........kdbbbkkbbbdk..........",
      "...........kkdbkkbdkk...........",
      ".............kkkkkk.............",
      "................................",
      "................................",
      "................................",
      "................................"
    ]
  },

  cricket: {
    w: 32, h: 32,
    palette: { "k": "#2a1a08", "d": "#5e4213", "b": "#94701f", "l": "#bf9a3a", "h": "#e2c56d", "e": "#fdf6d6" },
    rows: [
      "....ll....................ll....",
      "......ll................ll......",
      "........b..............b........",
      ".........b............b.........",
      "..........b..........b..........",
      "...........b........b...........",
      "............b......b............",
      ".............kkkkkk.............",
      "............kehbbbkk............",
      "............kklbbbdk............",
      "............klhbbbdk............",
      "..........dklhbbbbbdkd..........",
      ".........d.khhbbbbbdk.d.........",
      "........k..kbhbbbbbdk..k........",
      ".........ddkkbbbbbdkkdd.........",
      "........d..klhbbbbddk..d........",
      "......k.kl.klhbbbbddk.lk.k......",
      ".......klh.klhbbbbddk.hlk.......",
      "......klhh.klhbbbbddk.hhlk......",
      ".....klhhb.klhbbbbddk.bhhlk.....",
      ".....kdlhb.klhbbbbddk.bhldk.....",
      ".....kdblb.klhbbbbddk.blbdk.....",
      ".....kdbbb.klhbbbbddk.bbbdk.....",
      "......kdbb.klhbbbbddk.bbdk......",
      ".......kdb.klhbbbbddk.bdk.......",
      "........kk..kbhbbbdk..kk........",
      ".......d....kbhbbbdk....d.......",
      "......d......kbbbdk......d......",
      ".....k.......dkkkkd.......k.....",
      "............l......l............",
      "................................",
      "................................"
    ]
  },

  stagBeetle: {
    w: 32, h: 32,
    palette: { "k": "#170a05", "d": "#3c1a0b", "b": "#682d12", "l": "#93471c", "h": "#c06e2e", "e": "#f8dcae" },
    rows: [
      "................................",
      "..........hl........lh..........",
      "........lb............bl........",
      "......hlb..............blh......",
      ".....hlb................blh.....",
      ".....hld................dlh.....",
      "......lb.l............l.bl......",
      ".......lb..............bl.......",
      "........lb............bl........",
      ".........lb.l......l.bl.........",
      "..........lb.kkkkkk.bl..........",
      "...........kblhbbbddk...........",
      "..........keklhbbbdkkk..........",
      "..........kkbhbbbbbddk..........",
      "........dd.kbbbbbbddk.dd........",
      ".......k.kdlhhbbbbbbddk.k.......",
      "........kdlhehbbbbbbbddk........",
      "......ddkdblhbbbbbbbbddkdd......",
      ".....k..kkdbbbbbbbbbbdkk..k.....",
      ".......kdlhhbbbkkbbbbbddk.......",
      "......kdlhehbbbkkbbbbbbddk......",
      "......kdblhbbbbkkbbbbbbddk......",
      "....d.kdbbbbbbbkkbbbbbbddk.d....",
      "...k..kdbbbbbbbkkbbbbbbddk..k...",
      "......kdbbbbbbbkkbbbbbbddk......",
      ".......kdbbbbbbkkbbbbbddk.......",
      "........kdbbbbbkkbbbbddk........",
      ".........kdbbbbkkbbbddk.........",
      "..........kkdbbkkbddkk..........",
      "............kkkkkkkk............",
      "................................",
      "................................"
    ]
  },

  firefly: {
    w: 32, h: 32,
    palette: { "k": "#0c1017", "d": "#1c232e", "b": "#333e4d", "l": "#526073", "h": "#8494a6", "e": "#e2ebf5", "q": "#5c4113", "z": "#99691c", "o": "#d08a1c", "a": "#ffbe3c", "g": "#ffe98f", "w": "#fffbe0" },
    rows: [
      "................................",
      "............l......l............",
      "............b......b............",
      ".............b....b.............",
      ".............kkkkkk.............",
      "............kelbbbkk............",
      "............kklbbbdk............",
      "...........khlbbbbddk...........",
      "........ddkhlbbbbbbddkdd........",
      ".......k..klbbbbbbbbdk..k.......",
      ".........khlbbbkkbbbddk.........",
      "......ddkhelbbbkkbbbbddkdd......",
      ".....k..khlbbbbkkbbbbbdk..k.....",
      "........klbbbbbkkbbbbbdk........",
      "......ddklbbbbbkkbbbbbdkdd......",
      "....k...klbbbbbkkbbbbbdk...k....",
      "........klbbbbbkkbbbbbdk........",
      ".......qzkbbbbbkkbbbbdkzq.......",
      ".......qzzoaggggggggaozzq.......",
      "......qzzoagwwgggggggaozzq......",
      "......qzzoagggggggggaaozzq......",
      "......qzzoaagggggggaaoozzq......",
      ".......qzzoaggggggaaoozzq.......",
      "........qzooagggggaaoozq........",
      ".........qzoaaggggaaozq.........",
      ".........qzooaaaaaaoozq.........",
      "..........qzooaaaaoozq..........",
      "...........qzoooooozq...........",
      "............qzzzzzzq............",
      ".............qqqqqq.............",
      "................................",
      "................................"
    ]
  },

  mantis: {
    w: 32, h: 32,
    palette: { "k": "#0e2a18", "d": "#1e5231", "b": "#34804b", "l": "#57ab68", "h": "#8bd38f", "e": "#f2ffe4", "p": "#cfeb8c" },
    rows: [
      "......h..................h......",
      ".......l................l.......",
      "........l..............l........",
      ".........b............b.........",
      "..........kkkkkkkkkkkk..........",
      ".........kepkbhbbbdkppk.........",
      ".........kpkkbbbbbdkkpk.........",
      "...........kklbbbbdkk...........",
      "............kbhbbbdk............",
      "...........hhlkhbklhh...........",
      ".........hh...kbbk...hh.........",
      "........h.....kbbk.....h........",
      "........kh....kbbk....hk........",
      "..........hh..kbbk..hh..........",
      "............hlkbbklh............",
      ".............klbbdk.............",
      "..........ddklhbbbdkdd..........",
      "........dd..klhbbbdk..dd........",
      "......kd...klhbbbbbdk...dk......",
      ".........ddklhbbbbbdkdd.........",
      ".......dd..kbhbbbbbdk..dd.......",
      ".....kd....kbbbbbbbdk....dk.....",
      "...........klhbkkbbdk...........",
      "...........klbbkkbbdk...........",
      "............klbkkbdk............",
      "............kbbkkbdk............",
      "............kbbkkbdk............",
      ".............kbkkdk.............",
      ".............kkkkkk.............",
      "............l......l............",
      "................................",
      "................................"
    ]
  },

  cicada: {
    w: 32, h: 32,
    palette: { "k": "#0d1408", "d": "#26311a", "b": "#45542f", "l": "#6f8449", "h": "#a2bd6e", "e": "#eef8d2", "v": "#2b3f47", "m": "#63838f", "n": "#9dbcc2" },
    rows: [
      "................................",
      "................................",
      "............d......d............",
      "...........kkkkkkkkkk...........",
      ".........keklhbbbbbdkkk.........",
      ".........kkkbhbbbbbdkkk.........",
      "........kdlhhbbbbbbbdddk........",
      ".....ddkdlhehbbbbbbbbdddkdd.....",
      "...kd..kdlhhbbbbbbbbbdddk..dk...",
      "......kdlhbbbbbkkbbbbbdddk......",
      "......dd.kmkbhbbbbbdkmk.dd......",
      "....dd..kmmkbbbbbbbdkmmk..dd....",
      "..kd...kmnmkbhbbbbbdkmnmk...dk..",
      "......kmnnmkbbbbbbbdkmnnmk......",
      "...ddkmvnnmkbbbbbbbdkmnnvmkdd...",
      ".kd.kmnvnnmkbhbbbbbdkmnnvnmk.dk.",
      "....kmnnvnmkbbbbbbbdkmnvnnmk....",
      "...kmnnvnnmklhbbbbbdkmnnvnnmk...",
      "...kmvnnvnmkbbbbbbbdkmnvnnvmk...",
      "...kmnnvnnmkbbbbbbbdkmnnvnnmk...",
      "....kmnvnnmklbbbbbbdkmnnvnmk....",
      "....kmnnvnmkbbbbbbbdkmnvnnmk....",
      ".....kmnvnmkbbbbbbbdkmnvnmk.....",
      "......kmnnmkbbbbbbbdkmnnmk......",
      ".......kmnm.kbbbbbdk.mnmk.......",
      "........kmn.kbbbbbdk.nmk........",
      ".........km..kbbbdk..mk.........",
      "..........kk.kbbbdk.kk..........",
      ".............kbbbdk.............",
      "..............kkkk..............",
      "................................",
      "................................"
    ]
  },

  queenBee: {
    w: 32, h: 32,
    palette: { "k": "#1a1206", "n": "#2b2010", "d": "#6b4a10", "b": "#c08f16", "l": "#e8b32b", "h": "#ffd65e", "e": "#fff8dc", "w": "#55657b", "v": "#8ea3bc", "s": "#d8e6f4" },
    rows: [
      "............h..hh..h............",
      "............kehhhhlk............",
      "...........khehhhhldk...........",
      "...........kkkkkkkkkk...........",
      "........kd.knnnnnnnnk.dk........",
      "..........keknnnnnnkkk..........",
      "..........kkknlnnnnnkk..........",
      "...........knhhnnnndk...........",
      "............knnnnnnk............",
      "......dd.khehhhhhhllldk.dd......",
      "....kd...klhhbbbbbbbddk...dk....",
      ".....wvvvkbhbbbbbbbbddkvvvw.....",
      "...wvsvvvkbbbbbbbbbbddkvvvsvw...",
      ".wvvsvvvvkbbbbbbbbbbddkvvvvsvvw.",
      ".wvvvsvvvkbbbbbbbbbbddkvvvsvvvw.",
      "..wvvvsvv.klhhbbbbbbdk.vvsvvvw..",
      "...wvvsvvknnnnnnnnnnnnkvvsvvw...",
      "....wvsvvklhehbbbbbbbdkvvsvw....",
      ".....wvsvklhhbbbbbbbbdkvsvw.....",
      "......wvvknnnnnnnnnnnnkvvw......",
      ".....ddwvklhbbbbbbbbbdkvwdd.....",
      "...dd....kbbbbbbbbbbbdk....dd...",
      ".kd......knnnnnnnnnnnnk......dk.",
      "......dd.klhbbbbbbbbbdk.dd......",
      "....dd....kbbbbbbbbbdk....dd....",
      "..kd......knnnnnnnnnnk......dk..",
      "...........klhbbbbbdk...........",
      "...........knnnnnnnnk...........",
      "............klbbbbdk............",
      ".............knnnnk.............",
      "..............kddk..............",
      "...............kk..............."
    ]
  }
};
