// resources.sprites.js - hand-authored pixel art for the bug incremental.
// '.' is transparent and never appears in a palette. Every other glyph in
// `rows` maps to a #rrggbb value in that sprite's `palette`.
// Light source is top-left throughout; outlines are dark tints of the local
// hue, never pure black, so the art holds up over dark loam (#1a1209-#241a0e).
//
// The six 24x24 res* icons live side by side in the resource bar, so their
// silhouettes are deliberately pushed apart: tall droplet / angled leaf /
// round cluster / wide flat pool / domed caps / hard hexagon.

module.exports = {
  // ------------------------------------------------------------------
  // resSap (24x24) - Thick amber droplet mid-run: long stretched neck, fat
  // glossy bulb, one hard white-gold specular high on the left shoulder.
  resSap: {
    w: 24, h: 24,
    palette: {
      'k': '#3a2408',
      'd': '#6e430a',
      'b': '#ac6d14',
      'l': '#dc9f30',
      'h': '#f5cf62',
      'e': '#fff2c4',
      'g': '#ffffff',
    },
    rows: [
      '........................',
      '...........kk...........',
      '..........khlk..........',
      '..........kehk..........',
      '.........kehlbk.........',
      '.........kehlbk.........',
      '........keehlbdk........',
      '........keehlbdk........',
      '.......keehhlbbdk.......',
      '......keehhhllbbdk......',
      '......keegghhllbdk......',
      '.....keeegghhllbbdk.....',
      '.....keeehhhhllbbdk.....',
      '....keehhhhhlllbbddk....',
      '....kehhhhhllllbbddk....',
      '....khhhhllllbbbdddk....',
      '....khhhllllbbbbdddk....',
      '.....khhlllbbbbdddk.....',
      '.....kblllbbbbddddk.....',
      '......kblbbbbddddk......',
      '.......kbbbbddddk.......',
      '........kddddddk........',
      '........................',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // resLeaf (24x24) - Fresh leaf on a lower-left/upper-right diagonal. Pale
  // midrib runs tip to base, three short side veins, one bite out of the
  // upper-right edge, short woody stem trailing off the bottom-left.
  resLeaf: {
    w: 24, h: 24,
    palette: {
      'k': '#12300f',
      'd': '#1d5518',
      'b': '#2f8a26',
      'l': '#4fb536',
      'h': '#7fd254',
      'e': '#c6f38c',
      'r': '#5a4418',
    },
    rows: [
      '........................',
      '........................',
      '........................',
      '...............khhelk...',
      '.............khhhellbk..',
      '...........kehhhelllbk..',
      '..........kehhhelllbk...',
      '........kehhhhelk.......',
      '.......kehhhhelk........',
      '......kehhhhelllbbk.....',
      '.....kehhhhehlllbbk.....',
      '....kehhhhellllbbk......',
      '....khhhhellllbbk.......',
      '...khhhhellllbbk........',
      '...khhhehlllbbk.........',
      '...khhelllbbdk..........',
      '...khellbbdk............',
      '....kelbdk..............',
      '.....kdk................',
      '....krk.................',
      '...krk..................',
      '..krk...................',
      '.krk....................',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // resPollen (24x24) - Loose clump of four powdery grains of different
  // sizes, each with its own small highlight, with 1px motes drifting off.
  resPollen: {
    w: 24, h: 24,
    palette: {
      'k': '#4a2c06',
      'd': '#8a5a0c',
      'b': '#c6851a',
      'l': '#e5a92a',
      'h': '#f8ca50',
      'e': '#ffe89c',
      'g': '#fffbe4',
    },
    rows: [
      '........................',
      '.............b..........',
      '.....kkk................',
      '....kghlk.......kkk.....',
      '...kgghlbk.....kehlk....',
      '...khhhldk....kgghlbk...',
      '...klllbdk...kegehlbdk..',
      '....kbddk....khhhhlbdk..',
      '.....kkk.....kllllbddk..',
      '.......kkkkk..kbbbddk...',
      '......keehlbk..kdddk....',
      '.....kggehllbk..kkk.....',
      '.b..keggehllbdkkkkkk..b.',
      '....keeeehllbdkgghlbk...',
      '....khhhhhlbddkgehlbk...',
      '....klllllbbddkhhhlbk...',
      '....kblllbbdddklllbdk...',
      '.....kbbbddddkkbbbddk...',
      '......kdddddk..kkkkk....',
      '.......kkkkk............',
      '...............b........',
      '...b.................b..',
      '........b...............',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // resHoneydew (24x24) - Wide shallow pool, not a hanging drop: raised rim
  // catching light all the way round, a darker meniscus ring inside it, and
  // a hard white glint on the near-left of the surface.
  resHoneydew: {
    w: 24, h: 24,
    palette: {
      'k': '#4a3406',
      's': '#b8891f',
      'b': '#cf9f34',
      'l': '#e6c25e',
      'h': '#f6dd97',
      'e': '#fff3cf',
      'g': '#ffffff',
    },
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '........kkkkkkkk........',
      '.....kkkeeeeeeeekkk.....',
      '....keeesssssssseeek....',
      '...kesssgeehllbbsssek...',
      '...keseegeehllbbbbsek...',
      '...khshhhhhllbbbbbshk...',
      '...khslllllbbbbbbbshk...',
      '...khsssbbbbbbbbssshk...',
      '....khhhsssssssshhhk....',
      '.....kkkhhhhhhhhkkk.....',
      '........kkkkkkkk........',
      '........................',
      '........................',
      '........................',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // resFungus (24x24) - Three pale mushrooms, the only cool desaturated icon
  // in the set. Domed caps with a suggestion of gills along the cap edge,
  // short thick stems, one button in front at the lower left.
  resFungus: {
    w: 24, h: 24,
    palette: {
      'k': '#4a3c4c',
      'm': '#5a4a5e',
      'd': '#6d5c69',
      's': '#8b7a86',
      'b': '#a99aa2',
      'l': '#c8bcc0',
      'h': '#e2d8d6',
      'e': '#fbf6f2',
    },
    rows: [
      '........................',
      '........................',
      '........................',
      '........................',
      '........................',
      '......kkkkk.............',
      '....kkehhlbkk...........',
      '...keeehllbbsk..........',
      '..klhhhlllbssdk.........',
      '..klllllbbssddk.........',
      '.kmdmdmdmdmdmdmk........',
      '......klbsk.............',
      '......klbsk....kkkkk....',
      '......klbsk..kkehhlbkk..',
      '......klbsk..klhllbsdk..',
      '......klbsk.kmdmdmdmdmk.',
      '..kkk.klbsk....klsk.....',
      '.khlbkklbsk....klsk.....',
      '.kdmdkklbsk....klsk.....',
      '..klk.klbsk....klsk.....',
      '..klk.kkkkk....klsk.....',
      '..klk..........kkkk.....',
      '..kkk...................',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // resWax (24x24) - One honeycomb cell: the only angular, built-looking
  // shape in the set. Thick pale cream wall, lit on the upper-left facets,
  // with the recess inside shadowed at the top and catching light low down.
  resWax: {
    w: 24, h: 24,
    palette: {
      'k': '#3d2b05',
      'd': '#5f4410',
      's': '#97701c',
      'b': '#c9a349',
      'l': '#e4c87c',
      'h': '#f6e3ae',
      'e': '#fffaea',
      'g': '#ffffff',
    },
    rows: [
      '........................',
      '........................',
      '...........kk...........',
      '.........kkeekk.........',
      '.......kkegeehhkk.......',
      '.....kkegeekkhhllkk.....',
      '...kkeehhkkddkkhllbkk...',
      '...kehhkkddddddkklbbk...',
      '...khhkddddddddddklbk...',
      '...khlkdddddddddsklbk...',
      '...khlkdddddddsssklbk...',
      '...kllkdddddssssskbbk...',
      '...klbkdddssssssskbbk...',
      '...klbkdssssssssskbbk...',
      '...kbbksssssssssskbbk...',
      '...kbbbkksssssskkbbsk...',
      '...kbbbbbkksskkbbbssk...',
      '.....kkbbsskksssskk.....',
      '.......kkbssssskk.......',
      '.........kksskk.........',
      '...........kk...........',
      '........................',
      '........................',
      '........................',
    ],
  },
  // ------------------------------------------------------------------
  // iconScroll (16x16) - Queen's task. Aged parchment part-unrolled between
  // two darker rolled ends, three suggested lines of writing.
  iconScroll: {
    w: 16, h: 16,
    palette: {
      'k': '#2a1d0c',
      'w': '#5c3f18',
      'd': '#6b4a1c',
      'b': '#9b7434',
      'l': '#c9a866',
      'h': '#e8d5a4',
      'e': '#fff6dd',
    },
    rows: [
      '................',
      '................',
      '...kkkkkkkkk....',
      '..kehhhhhlbdk...',
      '..klbbbbbbddk...',
      '...kehhhhhlk....',
      '...khwwwwllk....',
      '...khhhhhhlk....',
      '...khwwwwwlk....',
      '...khhhhhhlk....',
      '...khwwwlllk....',
      '...klllllbbk....',
      '..kehhhhhlbdk...',
      '..kbbbbbbdddk...',
      '...kkkkkkkkk....',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconSilo (16x16) - Storage capacity. Terracotta jar with a lidded neck
  // and a banded hoop round its belly.
  iconSilo: {
    w: 16, h: 16,
    palette: {
      'k': '#2a1408',
      'd': '#582610',
      's': '#8d3f18',
      'b': '#c26a30',
      'l': '#e08f4e',
      'h': '#f2b478',
      'e': '#ffdcb0',
    },
    rows: [
      '................',
      '.....kkkkkk.....',
      '....kehhlbdk....',
      '...klllbbbddk...',
      '.....khhlbk.....',
      '...kehhhllbdk...',
      '..kehhhhllbbdk..',
      '..khhhhlllbbdk..',
      '..kddssssssddk..',
      '..kdssssssdddk..',
      '..khhhlllbbbdk..',
      '..khhlllbbbddk..',
      '...klllbbbddk...',
      '...klbbbbdddk...',
      '....kbbddddk....',
      '.....kkkkkk.....',
    ],
  },
  // ------------------------------------------------------------------
  // iconSpeed (16x16) - Double chevron pointing right. Purely graphic, with
  // a 1px bright leading edge along the top arm of each chevron.
  iconSpeed: {
    w: 16, h: 16,
    palette: {
      'k': '#10262e',
      'b': '#2f9fc0',
      'l': '#5fd0e6',
      'h': '#9ceef8',
      'e': '#e8fdff',
    },
    rows: [
      '................',
      '................',
      '.kkk....kkk.....',
      'kehlk..kehlk....',
      '.kehlk..kehlk...',
      '..kehlk..kehlk..',
      '...kehlk..kehlk.',
      '....kehlk..kehlk',
      '....khlbk..khlbk',
      '...khlbk..khlbk.',
      '..khlbk..khlbk..',
      '.khlbk..khlbk...',
      'khlbk..khlbk....',
      '.kkk....kkk.....',
      '................',
      '................',
    ],
  },
};
