// ui.sprites.js - hand-authored pixel art for the bug incremental.
// '.' is transparent and never appears in a palette. Every other glyph in
// `rows` maps to a #rrggbb value in that sprite's `palette`.
// Light source is top-left throughout; outlines are dark tints of the local
// hue, never pure black, so the art holds up over dark loam (#1a1209-#241a0e).

module.exports = {
  // ------------------------------------------------------------------
  // heroBeetle (64x64) - Rhinoceros beetle, top-down dorsal, head up. Curved forked head horn over a
  // smaller thoracic horn, armored pronotum, ridged glossy elytra with a central
  // seam, six jointed legs with tarsal claws, short clubbed antennae.
  heroBeetle: {
    w: 64, h: 64,
    palette: {
      'k': '#170c04',
      'd': '#331708',
      's': '#57290f',
      'b': '#7c4018',
      'l': '#a75e26',
      'h': '#d28d46',
      'e': '#f4debb',
      'g': '#fff8e6',
      'a': '#c9793a',
    },
    rows: [
      '................................................................',
      '................................................................',
      '.............................ek..ke.............................',
      '.............................hk..kh.............................',
      '.............................kehbsk.............................',
      '.............................kehbsk.............................',
      '......k.....................kehhbsdk.....................k......',
      '......kk....................kehhbsdk....................kk......',
      '......kk.......kkkkk........kehhbsdk........kkkkk.......kk......',
      '......kbk......kelbk.......keehhbssdk.......kssbk......ksk......',
      '.......kbk.....khldk.......keehhbssdk.......kdsbk.....ksk.......',
      '.......kbk.....khlbbk......keehhbssdk......ksssbk.....ksk.......',
      '.......kbbk....kkkbbbk....keehhhbbssdk....kssskkk....kssk.......',
      '......kbhlk.......kbbbk...keehhhbbssdk...ksssk.......ksbsk......',
      '......kbddbk.......kbbk...keehhhbbssdk...kssk.......ksddsk......',
      '......kbddbbk.......kblklkehhhbbbbsssdkskdsk.......kssddsk......',
      '.......kbbbbk.......kkkkhhhhhhhhbbbbbbbbkkkk.......kssssk.......',
      '........kbbbbk.......kgkllllkhehhbsksssskak.......kssssk........',
      '........kbbhlbkk.....kkkbbbkheehhbsskssskkk.....kkssbssk........',
      '........kbbddbbbkkk..kssssskheehhbsskdddddk..kkksssddssk........',
      '........kbbddbbbbhekkehhhekheehhhbbsskbbssakkddssssddssk........',
      '.........kbbbbbbllhhhhhhhekhlehhbbbsskbllllllldddsssssk.........',
      '..........kkbbblllleeeeehhksllhhbbssdkbbbbsssssdddsskk..........',
      '............kbblllegggeeehhsllhbbbssdbbbbblssssdddsk............',
      '............kkhllhegggeeehhhhhhhhllllbbblhhhlssddakk............',
      '..............kelhegggeeehhhhhhhhllllbbllhhhllsdak..............',
      '..............kelhheeeeehhhhhhhhhllllbbllhhhllsdak..............',
      '..............kellhhhhhhhhhehhhhhllllbblllllllsdak..............',
      '...............kellhhhhhhhssehhhhlllssbblllllsdak...............',
      '..............kbbllssbhbbllllbbbbssssdddddldddddsk..............',
      '............kkbbbbkkkkkkkkkkkkkkkkkkkkkkkkkkkkdssskk............',
      '..........kkbbbbbblhhhhhhhlbbkkkkkklhhllbbssddddsssskk..........',
      '..........kbhlblbhhheeehhhhbbssssssllhhllbblbbbddssbsk..........',
      '.........kbbddbbhhhhheeehhhbbsbbbbbllhhllllbbbbbdsddssk.........',
      '.........kbbddbhhhhhhheeehhhssddddbllhhlllbbbbbbbdddssk.........',
      '.........kbbbbbbhhbehgeeebehsssddbbllhbhllhbbdlbddssssk.........',
      '.........kbbbbbbhhbegggeebehhssddbbllhbhllhhbdldddssssk.........',
      '.........kbbbbbbhegggggeelehhssddbbllhbhlhhhhbhlddssssk.........',
      '........khlbbkhbhegggggeelehhssddbbllhbhlhhhhbhldaksssbk........',
      '........kddbk.khhelgggeeelehhssddbbllhbhlhhhhbhlak.ksddk........',
      '........kddbk.khhhlgggeeebehhssddbbllhbhlhhhhbhlak.ksddk........',
      '.......kbbbk..khhhleeeeeebehhssddbbllhbhlhhhhbhlak..ksssk.......',
      '.......kbbbk...khheleeeeebehhsbddbbllhbhllhhbhllk...ksssk.......',
      '.......kbbkk.kkhbhhleeeehbehbsbddbbllhbhllhhbhllakk.kkssk.......',
      '.......kbk..kbbblhhbeeehhbehbsbddbbllhbhllllshlddssk..ksk.......',
      '......kbkbkkbbbbbbhhbehhhbebbsbddbblhhshlllshlldsssskksksk......',
      '......kk.kbbbhlbbbhhbehhhbebbsbddbblhhshlllshlldssbsssk.kk......',
      '......kk.kbbbddbbabhhbehhhslbsbddbllhbhlblshllassddsssk.kk......',
      '..........kbbddbkklbhbehhldbsdsddsbblslbsddhdakksddssk..........',
      '..........kbbbbk..klbshhlldlsdsddsbbldlssddsak..kssssk..........',
      '..........kbbbbk...klbshhldlsdsddsbbldlsddsak...kssssk..........',
      '..........kbbbk....klbshhldlsdsddsbbldlsddsak....ksssk..........',
      '.........khlbbk.....kabbealsbssddsblbladdsak.....ksssbk.........',
      '.........kddbk.......kaassssssssssssssssaak.......ksddk.........',
      '.........kddbk........kkaaddddddddddddaakk........ksddk.........',
      '.........kbbk...........kkaaddddddddaakk...........kssk.........',
      '.........kbbk.............kkaaaaaaaakk.............kssk.........',
      '.........kbbk...............kkkkkkkk...............kssk.........',
      '.........kbbbk....................................ksssk.........',
      '........kbkkkbk..................................kskkksk........',
      '........kk...kbk................................ksk...kk........',
      '.......kkk....kk................................kk....kkk.......',
      '................................................................',
      '................................................................',
    ],
  },
  // ------------------------------------------------------------------
  // honeyBug (32x32) - Rare bonus pickup. Molten-gold scarab with a warm 1px glow rim.
  honeyBug: {
    w: 32, h: 32,
    palette: {
      'k': '#2c1704',
      'd': '#6a3b06',
      's': '#9c650f',
      'b': '#cd9420',
      'l': '#eabb3e',
      'h': '#f9de79',
      'e': '#fff5c8',
      'g': '#fffdf2',
      'w': '#96590c',
    },
    rows: [
      '................................',
      '................................',
      '.............wwwwww.............',
      '...........wwwkkkkwww...........',
      '..........weghlhlbkkww..........',
      '.....kkkk.wklhehhlbskw.kkkk.....',
      '.....ksbskkddddddddddkkdddk.....',
      '.....kksssbhhhehllbssddddkk.....',
      '......wkbhehhhehhllbbssdkw......',
      '......wkheeehhhhhlllllsdkw......',
      '......wklhehhhhhhlllllsdkw......',
      '......wkldddddddddddddddkw......',
      '......wwkddddddddddddddkww......',
      '.....wwkbhhhhbsdblhlbsddkww.....',
      '....wwkblhehhhsddblhlbsddkww....',
      '....wkblhegehhsddblhllbsddkw....',
      '....ksblesggehhddblhlhdsdddk....',
      '....ksblesgeehhddbllhhdldddk....',
      '....ksbleseeehhddbllhhdldddk....',
      '....ksblhseehhhddbllhhdldddk....',
      '....wkblhsehhhhddblllhdlddkw....',
      '....wwkblhshhhsddbllldlldkww....',
      '.....wkblhshhhsddblhldlddkw.....',
      '.....wkdslshhsdddblbsddddkw.....',
      '.....ksblllslsdddblbddllddk.....',
      '.....ksskklllbdddblsllkkddk.....',
      '.....kskwwkkllllllllkkwwkdk.....',
      '.....kk..wwwkkkkkkkkwww..kk.....',
      '...........wwwwwwwwww...........',
      '................................',
      '................................',
      '................................',
    ],
  },
  // ------------------------------------------------------------------
  // wasp (32x32) - Hostile invader. Pinched waist, yellow/black banding, stinger, spiky legs.
  wasp: {
    w: 32, h: 32,
    palette: {
      'k': '#140d04',
      'n': '#1e1a12',
      'o': '#342c1e',
      'p': '#54492f',
      'd': '#8a6a0e',
      'b': '#d9a814',
      'l': '#f3c92a',
      'h': '#ffe473',
      'e': '#fff8cf',
      'w': '#4d5a68',
      'v': '#8296a6',
      'u': '#c2d5e2',
    },
    rows: [
      '............n......n............',
      '.............n....n.............',
      '.............okkkko.............',
      '...k.......khhkpoookk.......k...',
      '....kkk....keekpooonk....kkk....',
      '.....knk...kopppooonk...knk.....',
      '......knkkknopppoonnnkkknk......',
      '.......knnnoopppooonnnnnk.......',
      '..kk....knlhppppoooobdnk....kk..',
      '....kkkknnhlppppoooodbnnkkkk....',
      '....kknnnnwoppppoooonwnnnnkk....',
      '......knnnwoopppooonnwnnnk......',
      '.....kvvvwnwnoppoonnwnwwwwk.....',
      '.....kvuwnnwnnoponnnwnnwwwk.....',
      '.....kuuuuwnnvoponwnnwnwwwk.....',
      '.....kuuuuwvlheehlbdwwnvvvk.....',
      '....kuuuuuwllhehhlbbdwvvvvvk....',
      '...knvwuvwooppppoooonnwvvvwnk...',
      '...kvwvvvwooppppoooonnwwwwwwk...',
      '..kvwvvvvkllhhehhllbbdkwwwwwwk..',
      '..kvwkvvk.klhhehhllbbk.kwwkwwk..',
      '..kwk.kvk..kopppooonk..kwk.kwk..',
      '..kvk.kvk..kopppooonk..kwk.kwk..',
      '..kk..kwk...kheehlbk...kwk..kk..',
      '......kk.....khelbk.....kk......',
      '......kk.....kppook.....kk......',
      '......kk......kkkk......kk......',
      '..............kppk..............',
      '...............pk...............',
      '...............pk...............',
      '...............pk...............',
      '................................',
    ],
  },
  // ------------------------------------------------------------------
  // mothPale (32x32) - Luna-style moth. Scalloped wings, streaming tails, feathery antennae.
  mothPale: {
    w: 32, h: 32,
    palette: {
      'k': '#3a3552',
      'q': '#635f86',
      's': '#8b93a8',
      'b': '#aebfba',
      'l': '#cfe0d6',
      'h': '#e8f4ea',
      'e': '#ffffff',
      'p': '#a892c8',
      'v': '#7d6aa8',
    },
    rows: [
      '................................',
      '..........p..........v..........',
      '.........lp.p......v.vs.........',
      '..........l.p......v.s..........',
      '...........ll.p..v.ss...........',
      '.............lp..vs.............',
      '..............llbs..............',
      '..........kkkkkelkkkkk..........',
      '.......kkklllhlblbqbbbkkk.......',
      '.....kkhehhhslbslbqqbbbbskk.....',
      '....kvheeehhhbsslbqlqqbbbsvk....',
      '..kkbllhehhhhhbelqlllbqqqbbskk..',
      '.kvbbsspvhlhhsbelqqllbpvpqqssvk.',
      '.kvsslpvhvpsshbelqlqqpvhvpbqqvk.',
      '..kvbllpvpshhhbelqlllqpvpbbsvk..',
      '...kbbllssllhhbelqllbbqqbbssk...',
      '...kbblsllllqqbelqqqbbbbqbssk...',
      '....ksslllqqhsbelqqlqqbbbqqk....',
      '...ksbllqqllshkelklqbbqqbbsqk...',
      '....kbqqlllshk.kk.klqbbbqqsk....',
      '.....kbbllslhk.kk.klbqbbssk.....',
      '.....kssbbsblk.kk.kbsqssqqk.....',
      '......kkssbbbk.kk.ksssqqkk......',
      '........ksbbsk.kk.kqssqk........',
      '.........ksbsk....kqsqk.........',
      '..........kssk....kqqk..........',
      '.........hhhh......bbbb.........',
      '.........hhhh......bbbb.........',
      '.........hhh........bbb.........',
      '.........ll..........ss.........',
      '........lll..........sss........',
      '........pp............vv........',
    ],
  },
  // ------------------------------------------------------------------
  // iconMagnifier (16x16) - Magnifying glass - brass rim, pale lens, diagonal glint.
  iconMagnifier: {
    w: 16, h: 16,
    palette: {
      'k': '#241505',
      'r': '#6b4410',
      'm': '#a87a22',
      'n': '#e0b855',
      'e': '#fff0c0',
      'd': '#3c5464',
      'b': '#7fa0b4',
      'l': '#c8e2ee',
      'g': '#ffffff',
    },
    rows: [
      '................',
      '....kkkk........',
      '...keennk.......',
      '..knlglbmk......',
      '.knegllbbmk.....',
      '.kngllbbbmk.....',
      '.kmllbbbdrk.....',
      '.kmbbbdddrk.....',
      '..kmbdddrk......',
      '...kmmrrknk.....',
      '....kkkk.knmk...',
      '..........knmk..',
      '...........knmk.',
      '............knmk',
      '.............kkk',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconSugar (16x16) - Isometric sugar cube with two loose crystals.
  iconSugar: {
    w: 16, h: 16,
    palette: {
      'k': '#2b2b36',
      'd': '#5e6478',
      's': '#7e8598',
      'b': '#b9c0d1',
      'l': '#eaeff8',
      'e': '#ffffff',
    },
    rows: [
      '.............kkk',
      '.............klk',
      '......keek...kkk',
      '....keellllk....',
      '..keellllllllk..',
      '..kbllllllllsk..',
      '..kbbbllllsssk..',
      '..kbbbbbsssssk..',
      '..kbbbbbsssssk..',
      '..kbbbbbsssssk..',
      '..kbbbbbsssssk..',
      '..kbbbbbdddddk..',
      'kkk.kbbbdddk....',
      'klk...kbdk......',
      'kkk.............',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconLeaf (16x16) - Leaf with a midrib and a bite out of the edge.
  iconLeaf: {
    w: 16, h: 16,
    palette: {
      'k': '#12300f',
      'd': '#245c1e',
      'b': '#3d8a2c',
      'l': '#5fb03e',
      'h': '#8fd05e',
      'e': '#d6f0a8',
      'r': '#5a4418',
    },
    rows: [
      '................',
      '................',
      '.........khlk...',
      '.......kehhhdk..',
      '.....keehhhldk..',
      '....keehhhlldk..',
      '...kehhhlldbk...',
      '..khhhldbbbk....',
      '.....khdbbk.....',
      '....kdbbbk......',
      '..kldbbdk.......',
      '...kdbdk........',
      '....kdk.........',
      '...krk..........',
      '..krk...........',
      '.krk............',
    ],
  },
  // ------------------------------------------------------------------
  // iconHoney (16x16) - Fat amber honey droplet.
  iconHoney: {
    w: 16, h: 16,
    palette: {
      'k': '#3a1c02',
      'd': '#8a4a06',
      's': '#b06e0e',
      'b': '#d4901a',
      'l': '#f0b431',
      'h': '#ffd166',
      'e': '#fff3c4',
      'g': '#ffffff',
    },
    rows: [
      '................',
      '.......kk.......',
      '.......khk......',
      '......khlk......',
      '......kehlk.....',
      '.....kehhbk.....',
      '....keehlbdk....',
      '....kgehlbdk....',
      '...kegehlbbdk...',
      '...khehhlbbdk...',
      '...khhhllbbdk...',
      '...kbhllbbddk...',
      '....kbllbbdk....',
      '.....kbbsdk.....',
      '......kddk......',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconLantern (16x16) - Warm-glowing lantern, dark metal frame, amber glass.
  iconLantern: {
    w: 16, h: 16,
    palette: {
      'k': '#191410',
      'm': '#3c3833',
      'n': '#6d675e',
      'o': '#a89f92',
      'd': '#8a4e06',
      'b': '#d8901a',
      'l': '#f5bf3e',
      'e': '#fff2b8',
      'g': '#fffce8',
    },
    rows: [
      '................',
      '......kook......',
      '.....kn..nk.....',
      '....koonnnmk....',
      '....knnnmmmk....',
      '....kmddddmk....',
      '....knbeelmk....',
      '....knlgglmk....',
      '....knleelmk....',
      '....knblllmk....',
      '....kndbbdmk....',
      '....knddddmk....',
      '...koonnnnmmk...',
      '...knnnmmmmmk...',
      '....kkkkkkkk....',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconGear (16x16) - Steel cogwheel, eight teeth, round hub.
  iconGear: {
    w: 16, h: 16,
    palette: {
      'k': '#1c222a',
      'd': '#495663',
      'b': '#78879b',
      'l': '#a7b6c6',
      'h': '#d4dfe9',
      'e': '#f5fafd',
    },
    rows: [
      '................',
      '......kkkk......',
      '......khlk......',
      '...kh.khlk.lk...',
      '...khhhllbbbk...',
      '....kehllbbk....',
      '....khllbbdk....',
      '..klllkkkkdddk..',
      '..kblbkkkkdddk..',
      '....kbbbdddk....',
      '....kbbddddk....',
      '...kbbbdddddk...',
      '...kb.kbdk.dk...',
      '......kddk......',
      '......kkkk......',
      '................',
    ],
  },
  // ------------------------------------------------------------------
  // iconFlask (16x16) - Science flask, bubbling green liquid, cork.
  iconFlask: {
    w: 16, h: 16,
    palette: {
      'k': '#121a14',
      'd': '#3f5a4f',
      's': '#7d9a90',
      'l': '#c8dfd4',
      'e': '#ffffff',
      'n': '#1c6b24',
      'b': '#35a83c',
      'h': '#66db5c',
      'g': '#b2f79a',
      'c': '#8a5a22',
      'o': '#c08a44',
    },
    rows: [
      '................',
      '......kock......',
      '......kcck......',
      '......kslk......',
      '......kelk......',
      '......kslk......',
      '.....ksllsk.....',
      '.....kslldk.....',
      '....kellllsk....',
      '....ksghbnsk....',
      '...kshbbbnnsk...',
      '...kshbgbbnsk...',
      '..kshbbbbbnnsk..',
      '..ksbbbgbbnnsk..',
      '..knbbbbbnnnnk..',
      '..kkkkkkkkkkkk..',
    ],
  },
  // ------------------------------------------------------------------
  // iconCrown (16x16) - Gold crown, three points, red gem.
  iconCrown: {
    w: 16, h: 16,
    palette: {
      'k': '#2e1c02',
      'd': '#7a5208',
      'b': '#c08e14',
      'l': '#e7b62e',
      'h': '#ffd964',
      'e': '#fff4c0',
      'r': '#7a0f14',
      'm': '#c41f24',
      'p': '#ff6a63',
    },
    rows: [
      '................',
      '................',
      '.......kk.......',
      '..ke..kehk..ek..',
      '..khk.khlk.klk..',
      '..khhlhhhllbbk..',
      '..kehhhmmhllbk..',
      '..kehhmpmrlbbk..',
      '..khhllmrbbbdk..',
      '.khhllllbbbbdk..',
      '.kllllbbbbbbddk.',
      '.kddbbbbbbdddddk',
      '.kkkkkkkkkkkkkk.',
      '................',
      '................',
      '................',
    ],
  }
};
