// workers.sprites.js - hand-authored pixel art for the worker-caste tier.
// '.' is transparent and never appears in a palette. Every other glyph in
// `rows` maps to a #rrggbb value in that sprite's `palette`.
// Top-down (dorsal) view, head north, light source top-left; outlines are dark
// tints of the local hue, never pure black, so the art holds over dark loam.

module.exports = {
  // ------------------------------------------------------------------
  // leafcutter (32x32) - Atta worker hoisting a cut leaf fragment overhead like
  // a parasol. The green blade is the read: pale midrib, ragged cut edge, warm
  // red-brown ant beneath with a pinched waist and elbowed antennae framing it.
  leafcutter: {
    w: 32, h: 32,
    palette: {
      'k': '#221109',
      'd': '#4a2410',
      'b': '#7a3f18',
      'l': '#a35c26',
      'h': '#d08b44',
      'e': '#f2e2c0',
      'g': '#123a0e',
      'n': '#2f7a1c',
      'v': '#4fae2b',
      'p': '#7ed84a',
      'q': '#c2f58a',
    },
    rows: [
      '................................',
      '..............gggg..............',
      '............gpppqvvng...........',
      '..........gpppppqvvvnng.........',
      '.........gppppppqvvvvnng........',
      '.......gpqppppppqvvvvvnng.......',
      '........gqqpppppqvvvvvvnng......',
      '........gpqpppppqvvvvvnng.......',
      '.......gppppppppqvvvvvnng.......',
      '.....l...gppppppqvvvvnng..l.....',
      '......l...gpppppqvvvnng..l......',
      '.......h...gpppqvvvnng..h.......',
      '........d...ggpqqvngg..d........',
      '.........b...g.ggg.g..b.........',
      '..........b..kkkkkk..b..........',
      '......l.....kehhbbdk.....l......',
      '.......h....kkhbbkdk....h.......',
      '........k...klhbbbdk...k........',
      '.........d...kbbbdk...d.........',
      '..........ddklhbbbdkdd..........',
      '..........ddkbhbbbdkdd..........',
      '.........d..klhbbbdk..d.........',
      '........k.ddkkbbbbdkdd.k........',
      '.......h.d....kdbk....d.h.......',
      '......l.d....klhbdk....d.l......',
      '.......k....klhhbbdk....k.......',
      '......h....klhhbbbbdk....h......',
      '.....l.....khehbbbbdk.....l.....',
      '...........klhbbbbbdk...........',
      '............kbbbbbdk............',
      '.............kbbbdk.............',
      '..............kkkk..............',
    ],
  },

  // ------------------------------------------------------------------
  // termiteWorker (32x32) - Pale soft-bodied worker. Cream and bone ramp with a
  // darker amber head capsule and open mandibles at the top, plump segmented
  // abdomen with dark fold bands, six short legs, no wings.
  termiteWorker: {
    w: 32, h: 32,
    palette: {
      'k': '#332312',
      'd': '#8a7048',
      'b': '#c4ab84',
      'l': '#e0cda6',
      'h': '#f2e6c8',
      'e': '#fffaee',
      'a': '#5c3410',
      'm': '#8a4e15',
      'o': '#c07a26',
      'w': '#e8a441',
    },
    rows: [
      '................................',
      '.............a....a.............',
      '.............am..ma.............',
      '............amoaaoma............',
      '...........kmowommaak...........',
      '..........okowwoommako..........',
      '.........m.kowooomaak.m.........',
      '........a..kmooommaak..a........',
      '...........kmmoommaak...........',
      '............kammmaak............',
      '............kdblbddk............',
      '........dddklhbbbbddkddd........',
      '......lk...klhbbbbddk...kl......',
      '...........khebbbbddk...........',
      '........dddklhbbbbddkddd........',
      '......lk...kdbbbbbddk...kl......',
      '...........klhbbbbddk...........',
      '.......dddklhbbbbbbddkddd.......',
      '.....lk...khebbbbbbddk...kl.....',
      '..........kddddddddddk..........',
      '..........klhbbbbbbddk..........',
      '..........khhbbbbbbddk..........',
      '..........kddddddddddk..........',
      '..........klhbbbbbbddk..........',
      '..........khebbbbbbddk..........',
      '..........kddddddddddk..........',
      '...........klhbbbbddk...........',
      '...........khbbbbbddk...........',
      '............kdbbbddk............',
      '.............kdbbdk.............',
      '..............kkkk..............',
      '................................',
    ],
  },

  // ------------------------------------------------------------------
  // honeyBee (32x32) - Forager in flight. Fuzzy amber/brown banded thorax, gold
  // and black striped abdomen, two pairs of wings swept out to the sides (cool
  // opaque grey-blue standing in for translucency), and a fat orange pollen
  // basket packed onto each hind leg.
  honeyBee: {
    w: 32, h: 32,
    palette: {
      'k': '#1c1208',
      'n': '#3a2a10',
      'd': '#7a5410',
      'b': '#c9911c',
      'l': '#edb833',
      'h': '#ffd76a',
      'e': '#fff6d2',
      'w': '#4a5a70',
      'v': '#8399b0',
      's': '#cfe0ee',
      'p': '#d96a08',
      'g': '#ffb42e',
    },
    rows: [
      '............n......n............',
      '.............n....n.............',
      '.............kkkkkk.............',
      '............knnnnnnk............',
      '............kennnnnk............',
      '......b.....knhnnnnk.....b......',
      '....b..l....knnnnnnk....l..b....',
      '.....l..n....knnnnk....n..l.....',
      '......n..ddklhhhhlddkdd..n......',
      '.......ddwskhehhhlddkswdd.......',
      '......wvvvsklhhhhlddksvvvw......',
      '...wvvsvvvskbdddddddksvvvsvvw...',
      '.wvvsvvvvvsklhhhhlddksvvvvvsvvw.',
      '.wvvvsvvvvskhehhhlddksvvvvsvvvw.',
      '...wvvvsvvskbdddddddksvvsvvvw...',
      '......wvvvsklhhhhlddksvvvw......',
      '............kdnnnndk............',
      '.........wsklhhhhlddksw.........',
      '.......wvvsknnnnnnnnksvvw.......',
      '......wvvvskhehhhlddksvvvw......',
      '.......wvvsknnnnnnnnksvvw.......',
      '.........wsklhhhhlddksw.........',
      '.........ddknnnnnnnnkdd.........',
      '........n..klhhhhlddk..n........',
      '.......pgg.khehhhlddk.ggp.......',
      '......pghg.knnnnnnnnk.ghgp......',
      '......pggg.klhhhhlddk.gggp......',
      '.......ppg..khhhhldk..gpp.......',
      '........pp..knnnnnnk..pp........',
      '.............klbbdk.............',
      '..............kddk..............',
      '...............kk...............',
    ],
  },

  // ------------------------------------------------------------------
  // waxScale (32x32) - Ceroplastes-style scale insect: a low domed mound of
  // secreted wax in concentric ridges, glossy crown spec up-left, warm rim on
  // the away edge. The small dark red insect just shows under the near lip.
  // Deliberately no splayed legs - only two stub tarsi - it does not run.
  waxScale: {
    w: 32, h: 32,
    palette: {
      'k': '#3a2a1e',
      'd': '#8d7f6d',
      'b': '#c2b6a2',
      'l': '#ded4bf',
      'h': '#f2ead6',
      'e': '#fffdf4',
      'r': '#3a0c09',
      'm': '#8a2213',
      'o': '#c4472a',
    },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...........kkkkkkkkkk...........',
      '.........kklddbbbbddlkk.........',
      '........kldbhhhhhhhhbdlk........',
      '.......klbhhhbbbbbbhhhblk.......',
      '......klbhhbeeeeeeelbhhdbk......',
      '.....klbhhbeeeeeleeeeblldbk.....',
      '.....kdhhbeeeeeeeeleehdlldk.....',
      '....klbhhleeeeeeeeebhhblldbk....',
      '....klbhbeeleeeeeehhbhhdldbk....',
      '....kdhhbeeleeeeehhhbhhdlldk....',
      '....kdhhbeeleeehhhhhbhhdlldk....',
      '....klbhbeeleehhhhhhbhhdldbk....',
      '....klbhhleelhhhhhhbhhblldbk....',
      '.....kdhhblhhbbhhbbhhbdlldk.....',
      '.....klbhhdbhhhhhhhhbdlldbk.....',
      '......klbllldbhhhhbdllldbk......',
      '.......kbdllllddddlllldbk.......',
      '........kkddroommmmrddkk........',
      '..........kkrommmmmrkk..........',
      '...........krmmmmmmrk...........',
      '...........r.rmmmmr.r...........',
      '..............rmmr..............',
      '................................',
      '................................',
      '................................',
    ],
  },

  // ------------------------------------------------------------------
  // grub (32x32) - Beetle larva curled into the classic comma. Cream-to-pink
  // segmented body with hard fat folds, amber head capsule with a tiny pair of
  // mandibles, three tiny true legs on the thoracic segments behind the head.
  grub: {
    w: 32, h: 32,
    palette: {
      'k': '#4a2d1d',
      'd': '#b08a76',
      'b': '#dcb8a4',
      'l': '#f0d5c0',
      'h': '#fbe9dc',
      'e': '#fffaf4',
      'a': '#4a2607',
      'm': '#8a4f14',
      'o': '#c78628',
      'w': '#f0be62',
    },
    rows: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..............kkkkkk............',
      '............kkkeehhbkkk.........',
      '...........keehhhhhbhhkk........',
      '..........awhhhhhhhhhhhlk.......',
      '.........awwwhlllllllllllk......',
      '........aawwolllllllllllllk.....',
      '........awwooobbbbdblllllllk....',
      '........awoooobbbbbblllllllk....',
      '........aoooommdddbbllllllbbk...',
      '........aooomaakkkkkllllllbbk...',
      '.........aaaaa..omakllllddbbk...',
      '.........o..o.......khllllbbk...',
      '..........mm.....omakhhllbbbk...',
      '....................khhllbbbk...',
      '.................omakhhdlbbdk...',
      '...................kehhlbbddk...',
      '.............kk..kkebhllbbdk....',
      '............kbbkkhhhhllbbdkk....',
      '...........kbbllhhhlllbbddk.....',
      '...........kddllllllbbbddk......',
      '............kbbbbbbbbddkk.......',
      '.............kkbbbbddkkk........',
      '...............kkkkkk...........',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
